apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-catalog-ui-operator
  labels:
      name: ibm-catalog-ui-operator
      app.kubernetes.io/instance: catalog-ui
      app.kubernetes.io/managed-by: cataloguis.operator.ibm.com
      app.kubernetes.io/name: cataloguis.operator.ibm.com
subjects:
- kind: ServiceAccount
  name: ibm-catalog-ui-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-catalog-ui-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-catalog-ui-operator
  labels:
      name: ibm-catalog-ui-operator
      app.kubernetes.io/instance: cataloguis.operator.ibm.com
      app.kubernetes.io/managed-by: cataloguis.operator.ibm.com
      app.kubernetes.io/name: cataloguis.operator.ibm.com
subjects:
- kind: ServiceAccount
  name: ibm-catalog-ui-operator
  namespace: ibm-common-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-catalog-ui-operator