apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.catalogui.commonname }}
  labels:
    app: {{ .Values.catalogui.commonname  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "catalogui"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service}}
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: {{ .Values.catalogui.commonname }}
spec:
  ports:
    - name: {{ .Values.catalogui.service.name }}
      port: {{ .Values.catalogui.service.port }}
      targetPort: {{ .Values.catalogui.service.targetPort }}
  selector:
    k8s-app: {{ .Values.catalogui.commonname }}
