apiVersion: v1
kind: ServiceAccount
metadata: 
  name: catalog-ui-sa
  labels:
    app.kubernetes.io/instance: cataloguis.operator.ibm.com
    app.kubernetes.io/managed-by: cataloguis.operator.ibm.com
    app.kubernetes.io/name: {{ .Values.catalogui.commonname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalog-ui-privileged-role
  labels:
    app.kubernetes.io/instance: cataloguis.operator.ibm.com
    app.kubernetes.io/managed-by: cataloguis.operator.ibm.com
    app.kubernetes.io/name: {{ .Values.catalogui.commonname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints 
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-ui-privileged
  labels:
    app.kubernetes.io/instance: cataloguis.operator.ibm.com
    app.kubernetes.io/managed-by: cataloguis.operator.ibm.com
    app.kubernetes.io/name: {{ .Values.catalogui.commonname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
subjects:
- kind: ServiceAccount
  name: catalog-ui-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: catalog-ui-privileged-role